---
title: "경남 공모전(R version)"
output: html_document
date: "2023-08-09"
---
```{r}
library(olsrr)
library(MASS)
library(car)
```

```{r}
gn = read.csv("C:/Users/sos35/OneDrive/문서/R/변수종합-이상치 처리.csv", header=TRUE, sep=",")

# 모든 컬럼 이름 변경
names(gn) <- c("행정동", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "X8", "X9", "X10", "X11", "X12")

gn = data.frame(gn)
head(gn)
```


```{r}
# 산점도 확인 
plot(gn[-1])
```

```{r}
# 변수 치환
X1 = gn$X1
X2 = gn$X2
X3 = gn$X3
X4 = gn$X4
X5 = gn$X5
X6 = gn$X6
X7 = gn$X7
X8 = gn$X8
X9 = gn$X9
X10 = gn$X10
X11 = gn$X11
X12 = gn$X12
```

```{r}
# 다중공선성 확인(Vif)
fit = lm(X7~X1+X2+X3+X4+X5+X6+X8+X9+X10+X11+X12)
vif(fit)
```

```{r}
# StepAIC 방법을 적용
stepAIC(lm(X7~1, data=gn), X7~X1+X2+X3+X4+X5+X6+X8+X9+X10+X11+X12, direcion="both")
```

```{r}
# 마지막으로 추가된 X2변수를 넣은것과 안넣은 것에 대해 anova 검정
reg1 = lm(X7~0+X8+X11+X1+X5+X2)
summary(reg1)
```

```{r}
# backward 방식
reg0 = lm(X7~X1+X2+X3+X4+X5+X6+X8+X9+X10+X11+X12)
ols_step_backward_aic(reg0, progress=T,details=T) # backward 방식 사용하여도 stepAIC와 동일하게 결과 출력 
```

```{r}
reg1 = lm(X7~0+X1+X2+X5+X8+X9+X11+X12)
summary(reg1)
```


```{r}
# 전진선택법 - stepAIC와 동일한 결과
reg.F = lm(X7~X1+X2+X3+X4+X5+X6+X8+X9+X10+X11+X12)
ols_step_forward_aic(reg.F, progress = F, details = F) # 비교 기준이 AIC가 됨, 
```

```{r}
# 최종 모형(회귀진단)
reg1 = lm(X7~0+X8+X11+X1+X5+X2) # 전진선택, stepAIC
reg2 = lm(X7~0+X1+X2+X5+X8+X9+X11+X12) # 후진소거
reg3 = lm(X7~0+X8+X9+X11) # 라쏘
```

```{r}
fit = lm(X7~0+X8+X11+X1+X5+X2, x=T, y=T)
summary(fit)
par(mfrow = c(2, 3))
plot(fit, which = 1:6)
```

```{r}
fit1 = lm(X7~0+X1+X2+X5+X8+X9+X11+X12, x=T, y=T)
summary(fit1)
par(mfrow = c(2, 3))
plot(fit1, which = 1:6)
```

```{r}
fit2 = lm(X7~0+X8+X9+X11, x=T, y=T)
summary(fit2)
par(mfrow = c(2, 3))
plot(fit1, which = 1:6)
```
